spring:
  profiles:
    active: local
server:
  port: 8081
topics:
  retry: 'local.accounts.retry'
  dlt: 'local.accounts.dlq'

---
spring:
  profiles:
    active: local
  kafka:
    template:
      default-topic: local.accounts
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: events-listener-group
    producer:
      bootstrap-servers:
        -   localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true

