spring:
  profiles:
    active: local
server:
  port: 8082
topics:
  retry: 'local.accounts.retry'
  dlt: 'local.accounts.dlq'

---
spring:
  profiles:
    active: local
  kafka:
    template:
      default-topic: local.accounts
    consumer:
      bootstrap-servers: localhost:29092,localhost:29093
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: events-listener-group
      properties:
        schema.registry.url: http://localhost:8085
    producer:
      bootstrap-servers:
        - localhost:29092
        - localhost:29093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      schema.registry.url: http://localhost:8085
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true

